// Extract ABIs from compiled Foundry artifacts into typed `abis.ts` for the agent + web apps.
// Run after `forge build`:  node scripts/extract-abis.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "contracts", "out");

const NAMES = [
  "AgentRegistry",
  "ReceiptVerifier",
  "ReputationOracle",
  "CreditPolicy",
  "SettlementHook",
  "CreditLine",
  "MockUSDC",
];

const toConst = (n) => n.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();

function loadAbi(name) {
  const p = join(outDir, `${name}.sol`, `${name}.json`);
  return JSON.parse(readFileSync(p, "utf8")).abi;
}

let ts = "// AUTO-GENERATED by scripts/extract-abis.mjs — do not edit by hand.\n";
ts += "// Run `node scripts/extract-abis.mjs` after `forge build` to refresh.\n\n";
for (const name of NAMES) {
  ts += `export const ${toConst(name)}_ABI = ${JSON.stringify(loadAbi(name))} as const;\n\n`;
}

const targets = [
  join(root, "agent", "src", "generated"),
  join(root, "web", "lib", "generated"),
];
for (const t of targets) {
  mkdirSync(t, { recursive: true });
  writeFileSync(join(t, "abis.ts"), ts);
  console.log("wrote", join(t, "abis.ts"));
}
